name: geoface
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  uuid: ^4.5.1
  geolocator: ^14.0.0
  shared_preferences: ^2.5.3
  firebase_storage: ^12.4.5
  lottie: ^3.3.1
  intl: ^0.20.2
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  material_design_icons_flutter: ^7.0.7296
  image: ^4.5.4
  http: ^1.4.0
  image_picker: ^1.1.2
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
